nixbuild: use bash instead of fish
was getting:

error: can not save history
warning-path: Unable to locate data directory derived from $HOME: '/var/empty/.local/share/fish'.
warning-path: The error was 'Operation not permitted (os error 1)'.
warning-path: Please set $HOME to a directory where you have write access.